
import com.opencsv.CSVReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author joao.sintra
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public static String nomeFicheiro;

    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoEscolherFicheiro = new javax.swing.JButton();
        campoFicheiro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoEscolherFicheiro.setText("Escolher Ficheiro");
        botaoEscolherFicheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoEscolherFicheiroMousePressed(evt);
            }
        });
        getContentPane().add(botaoEscolherFicheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 30));

        campoFicheiro.setEditable(false);
        getContentPane().add(campoFicheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 260, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Importação de Férias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("*Ficheiro CSV com apenas o essencial, separado por virgulas");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 630, 30));

        botaoGuardar.setText("Guardar");
        botaoGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoGuardarMousePressed(evt);
            }
        });
        getContentPane().add(botaoGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 130, 30));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("nº de Func, datas e retirar o cabeçalho do CSV (onde fica o nome das colunas)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText(".txt");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEscolherFicheiroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEscolherFicheiroMousePressed

        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File(".")); //sets current directory

        int response = fileChooser.showOpenDialog(null); //select file to open
        //int response = fileChooser.showSaveDialog(null); //select file to save

        if (response == JFileChooser.APPROVE_OPTION) {
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            System.out.println(nomeFicheiro);
            nomeFicheiro = file.toString();
            campoFicheiro.setText(file.getName());
        }


    }//GEN-LAST:event_botaoEscolherFicheiroMousePressed

    private void botaoGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGuardarMousePressed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showSaveDialog(this);
        File ficheiro = fileChooser.getSelectedFile();

        try {
            FileWriter fw = new FileWriter(ficheiro);
            // Create an object of filereader
            // class with CSV file as a parameter.
            FileReader filereader = new FileReader(nomeFicheiro);

            // create csvReader object passing
            // file reader as a parameter
            CSVReader csvReader = new CSVReader(filereader);
            String[] nextRecord;

            // we are going to read data line by line
            while ((nextRecord = csvReader.readNext()) != null) {

                //System.out.println();
                String idUser = "" + nextRecord[0];
                int tamanho = nextRecord[0].length();
                //do while para adicionar 0 antes do nr de funcionario
                do {
                    idUser = "0" + idUser;
                    tamanho++;
                } while (tamanho < 5);

                System.out.println(idUser);
                SimpleDateFormat fromUser = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat myFormat = new SimpleDateFormat("ddMMyyyy");
                DateTimeFormatter caseInsensitiveDtf = new DateTimeFormatterBuilder().parseCaseInsensitive().appendPattern("dd-MMM-yy").toFormatter(Locale.ROOT);
                for (int i = 1; i <= 8; i++) {
                    if (nextRecord[i].isBlank()||nextRecord[i].isEmpty()) {
                        continue;
                    } else {
                        if (i == 7) {
                            LocalDate localDate = LocalDate.parse(nextRecord[7], caseInsensitiveDtf);
                            LocalDate localDate2 = LocalDate.parse(nextRecord[8], caseInsensitiveDtf);
                            String dataFerias01 = myFormat.format(fromUser.parse(localDate.toString()));
                            String dataFerias02 = myFormat.format(fromUser.parse(localDate2.toString()));
                            fw.write(idUser + dataFerias01 + dataFerias02 + "\n");
                        } else if (i == 8) {
                            System.out.println("8");
                        } else if (i % 2 == 1) {

                            LocalDate localDate = LocalDate.parse(nextRecord[i], caseInsensitiveDtf);
                            LocalDate localDate2 = LocalDate.parse(nextRecord[i + 1], caseInsensitiveDtf);
                            String dataFerias01 = myFormat.format(fromUser.parse(localDate.toString()));
                            String dataFerias02 = myFormat.format(fromUser.parse(localDate2.toString()));
                            fw.write(idUser + dataFerias01 + dataFerias02 + "\n");
                        }
                    }
                }
                //Escrita no ficheiro

            }

            fw.close();
            JOptionPane.showMessageDialog(null, "Ficheiro escrito com sucesso", "Messagem", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Messagem", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_botaoGuardarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEscolherFicheiro;
    private javax.swing.JButton botaoGuardar;
    private javax.swing.JTextField campoFicheiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
